name: Build and Test

on:
  push:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  find-stack-yamls:
    name: Find stack.yamls for GHC Matrix
    runs-on: ubuntu-22.04
    outputs:
      stack-yamls: ${{ steps.set-output.outputs.stack-yamls }}
    steps:
      - name: Find Stack Yamls
        id: set-output
        uses: flipstone/github-actions/find-stack-ghc-yamls@d3da7b6361e88fc10557f8b6ca9aaf44e13f0f8e

  build:
    name: Build and Test
    needs: find-stack-yamls
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 5
      matrix:
        stack-yaml: ${{ fromJson(needs.find-stack-yamls.outputs.stack-yamls) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        env:
          cache-version: v3
        with:
          key: ${{ env.cache-version }}-${{ matrix.stack-yaml }}-${{ hashFiles(matrix.stack-yaml, 'stack-base.yaml', '*/package.yaml') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ matrix.stack-yaml }}-
          path: |
            ./stack-root

      - name: Setup Stack
        uses: flipstone/github-actions/setup-dockerized-stack@d3da7b6361e88fc10557f8b6ca9aaf44e13f0f8e
        with:
          stack-root: ./stack-root

      - name: Build and test
        run: ./scripts/test --stack-yaml ${{ matrix.stack-yaml }}

  test-examples:
    name: Test Examples
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        env:
          cache-version: v3
        with:
          key: ${{ env.cache-version }}-examples-${{ hashFiles('**/examples/*/stack.yaml', '*/package.yaml', '**/examples/*/package.yaml') }}
          restore-keys: |
            ${{ env.cache-version }}-examples-
          path: |
            ./stack-root

      - name: Setup Stack
        uses: flipstone/github-actions/setup-dockerized-stack@d3da7b6361e88fc10557f8b6ca9aaf44e13f0f8e
        with:
          stack-root: ./stack-root

      - name: Test Examples
        run: ./scripts/test-examples

  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # This doesn't actually run stack, so we don't need a cached stack-root, but
      # we still need to set up the dockerized environment for scripts to be able
      # to run
      - name: Setup Stack
        uses: flipstone/github-actions/setup-dockerized-stack@d3da7b6361e88fc10557f8b6ca9aaf44e13f0f8e
        with:
          stack-root: ./stack-root

      - name: Format and Check for Diff
        run: ./scripts/format-repo
